/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./schema/context"




declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  FloatFilterInput: { // input type
    equals?: number | null; // Float
    gt?: number | null; // Float
    gte?: number | null; // Float
    lt?: number | null; // Float
    lte?: number | null; // Float
  }
  IncludeInput: { // input type
    reading?: boolean | null; // Boolean
    sensor?: boolean | null; // Boolean
    unit?: boolean | null; // Boolean
  }
  ReadingInputParams: { // input type
    include?: NexusGenInputs['IncludeInput'] | null; // IncludeInput
    value?: NexusGenInputs['FloatFilterInput'] | null; // FloatFilterInput
  }
  UnitInputParams: { // input type
    include?: NexusGenInputs['IncludeInput'] | null; // IncludeInput
    label?: string | null; // String
    name?: string | null; // String
    sensor_name?: string | null; // String
  }
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  Query: {};
  reading: { // root type
    id: number; // Int!
    sensor_id: number; // Int!
    value: number; // Int!
  }
  sensor: { // root type
    id: number; // Int!
    name: string; // String!
    unit_id: number; // Int!
  }
  unit: { // root type
    id: number; // Int!
    label: string; // String!
    name: string; // String!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  Query: { // field return type
    reading: NexusGenRootTypes['reading'][]; // [reading!]!
    sensor: NexusGenRootTypes['sensor'][]; // [sensor!]!
    unit: NexusGenRootTypes['unit'][]; // [unit!]!
  }
  reading: { // field return type
    id: number; // Int!
    sensor: NexusGenRootTypes['sensor'] | null; // sensor
    sensor_id: number; // Int!
    value: number; // Int!
  }
  sensor: { // field return type
    id: number; // Int!
    name: string; // String!
    readings: NexusGenRootTypes['reading'][][] | null; // [[reading!]!]
    unit: NexusGenRootTypes['unit']; // unit!
    unit_id: number; // Int!
  }
  unit: { // field return type
    id: number; // Int!
    label: string; // String!
    name: string; // String!
    sensor: NexusGenRootTypes['sensor'] | null; // sensor
  }
}

export interface NexusGenFieldTypeNames {
  Query: { // field return type name
    reading: 'reading'
    sensor: 'sensor'
    unit: 'unit'
  }
  reading: { // field return type name
    id: 'Int'
    sensor: 'sensor'
    sensor_id: 'Int'
    value: 'Int'
  }
  sensor: { // field return type name
    id: 'Int'
    name: 'String'
    readings: 'reading'
    unit: 'unit'
    unit_id: 'Int'
  }
  unit: { // field return type name
    id: 'Int'
    label: 'String'
    name: 'String'
    sensor: 'sensor'
  }
}

export interface NexusGenArgTypes {
  Query: {
    reading: { // args
      params?: NexusGenInputs['ReadingInputParams'] | null; // ReadingInputParams
    }
    unit: { // args
      params?: NexusGenInputs['UnitInputParams'] | null; // UnitInputParams
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}